import { describe, it, expect } from "vitest";
import { generateSlug, isValidSlug } from "@/lib/slug";

describe("generateSlug", () => {
  it.each([
    ["My Circle", "my-circle"],
    ["  Hello World  ", "hello-world"],
    ["café résumé", "cafe-resume"],
    ["événements à Paris", "evenements-a-paris"],
    ["L'été français", "l-ete-francais"],
    ["Hello---World", "hello-world"],
    ["Hello & World!", "hello-world"],
    ["123 Numbers", "123-numbers"],
    ["UPPERCASE", "uppercase"],
    ["  --dashes--  ", "dashes"],
    ["a".repeat(100), "a".repeat(80)],
  ])("should slugify %j to %j", (input, expected) => {
    expect(generateSlug(input)).toBe(expected);
  });

  it("should handle empty-ish input gracefully", () => {
    expect(generateSlug("   ")).toBe("");
    expect(generateSlug("---")).toBe("");
  });
});

describe("isValidSlug", () => {
  it.each([
    ["my-circle", true],
    ["hello-world-123", true],
    ["test", true],
    ["a", true],
    ["my-event-lxyz123", true],
  ])("should accept valid slug %j", (slug, expected) => {
    expect(isValidSlug(slug)).toBe(expected);
  });

  it.each([
    ["", false],
    ["https%3A%2F%2Fs4da3qkysw6xnvuo.public.blob.vercel-storage.com/covers/123.webp", false],
    ["https://example.com/image.webp", false],
    ["-leading-dash", false],
    ["trailing-dash-", false],
    ["double--dash", false],
    ["UPPERCASE", false],
    ["has spaces", false],
    ["has.dots", false],
    ["a".repeat(121), false],
  ])("should reject invalid slug %j", (slug, expected) => {
    expect(isValidSlug(slug)).toBe(expected);
  });

  it("should accept slugs generated by generateSlug", () => {
    const titles = ["Soirée JS Pizza", "Workshop React 19", "Café des devs"];
    for (const title of titles) {
      const slug = generateSlug(title);
      expect(isValidSlug(slug)).toBe(true);
    }
  });
});
